### ISSUE TITLE
can not use with vite-ssg

### ISSUE THREAD

**Issue by hyoban** [dsrkafuu/sakana-widget#7]
Not sure which is causing the problem, come here for help, thank you.

```
[vite-ssg] An internal error occurred.
[vite-ssg] Please report an issue, if none already exists: https://github.com/antfu/vite-ssg/issues
/home/hyoban/dev/ssg-sakana/node_modules/.pnpm/sakana-widget@2.2.2/node_modules/sakana-widget/lib/index.js:10
})(self, () => {
   ^

ReferenceError: self is not defined
    at Object.<anonymous> (/home/hyoban/dev/ssg-sakana/node_modules/.pnpm/sakana-widget@2.2.2/node_modules/sakana-widget/lib/index.js:10:4)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:170:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:198:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:385:24)
    at async build (file:///home/hyoban/dev/ssg-sakana/node_modules/.pnpm/vite-ssg@0.20.2_thgl23324gg75myoeph36y4c5a/node_modules/vite-ssg/dist/chunks/build.mjs:171:87)
 ELIFECYCLE  Command failed with exit code 1.
```

## minimal reproduction

https://github.com/hyoban/ssg-sakana

https://github.com/hyoban/ssg-sakana/commit/e99b063fb1630df60e064a9c6211c26ac12001a0

**Comment by dsrkafuu** [comment]
This is a client(browser) only library, SSR is not supported.

You need to use dynamic import(runtime):

```js
onMounted(() => {
  import('sakana-widget').then((pkg) => {
    const SakanaWidget = pkg.default
    new SakanaWidget().mount('#sakana-widget')
  })
})
```

**Comment by hyoban** [comment]
Thanks for your explanation, learned a lot
